# name: Lint

# on:
#   # Trigger the workflow on push or pull request,
#   # but only for the main branch
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main

# jobs:
#   run-linters:
#     name: Run linters
#     runs-on: ubuntu-latest

#     steps:
#       - name: Check out Git repository
#         uses: actions/checkout@v3

#       - name: Set up Node.js
#         uses: actions/setup-node@v1
#         with:
#           node-version: 16

#       # ESLint and Prettier must be in `package.json`
#       - name: Install Node.js dependencies
#         run: npm ci

#       - name: Run linters
#         uses: wearerequired/lint-action@v2
#         with:
#           eslint: true
#           prettier: true

name: Node.js CI

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Archive npm failure logs
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: npm-logs
          path: ~/.npm/_logs
      - name: Setup nNode.js
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm i
      - name: Run linting
        run: npm run lint
      - name: Run unit tests
        run: npm run test